### ISSUE TITLE
Ping spoof false flag

### ISSUE THREAD

**Issue by rafi67000** [artemisac/artemis-minecraft-anticheat#4]
**Describe the bug**
Pingspoof (protocol) falses like hell

**To Reproduce**
1. launch server
2. join on 1.8 and do nothing
3. enjoy alerts

**Screenshots**
![image](https://user-images.githubusercontent.com/80040363/222166973-48f8e368-e47d-4c62-be1d-2704e08328e7.png)

**Comment by TawnyE** [comment]
which one did you do the first one or the second jar

**Comment by terminalsin** [comment]
> **Describe the bug** Pingspoof (protocol) falses like hell
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. launch server
> 2. join on 1.8 and do nothing
> 3. enjoy alerts
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/80040363/222166973-48f8e368-e47d-4c62-be1d-2704e08328e7.png)

Not a false; You either have a broken client, either a broken proxy.
